[package]
name = "void-vessels"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
serde.workspace = true
glam.workspace = true
rapier3d.workspace = true
void-assembly.workspace = true
void-environment.workspace = true
void-orbit.workspace = true
void-landing.workspace = true
void-rotation.workspace = true
void-sas.workspace = true
void-terrain.workspace = true
void-frames.workspace = true
void-modules.workspace = true

[dev-dependencies]
serde_json.workspace = true
