[package]
name = "void-view"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
glam.workspace = true
void-orbit.workspace = true
void-frames.workspace = true

[dev-dependencies]
void-testkit.workspace = true
void-landing.workspace = true
void-lod.workspace = true
void-terrain.workspace = true
